### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by kiteloopdesign** [adept/full-fledged-hledger#21]
First of all let me congratulate you for such an amazing work you have done here. Not only from the technical but also from the communication perspective. Common issues and topics truly well broken out and explained in an accessible way.

Let me add that I found following reference on [this](https://github.com/adept/full-fledged-hledger/wiki/Investments-easy-approach) wiki page to be broken

```
    Good set of articles on IRR, TWR, value of money, disconting, EAR etc on Investopedia: https://www.investopedia.com/exam-guide/cfa-level-1/quantitative-methods/default.asp
```
Could not find a good replacement for it, just individual pages on IRR,TWR, etc.

Thanks and looking forward for more articles! Maybe some example about how to directly track stocks and/or Bitcoin ?

**Comment by adept** [comment]
Thank you for your kind words! I've pushed the change that tries to provide a set of alternative links just now.

I have a setup for the cryptocurrency tracking that is a bit clunky, which is why I haven't written it up yet. But thanks for the nudge, maybe it will provide me with the missing inspiration :)
